export const NEWS_LIST = [
  {
    id: 1,
    avatar: '/assets/images/avatar-placeholder.png',
    title: 'Update tình trạng giao thông Hà Nội ngày 12 tháng 6',
    date: '2 days ago',
    image: '/assets/images/news_1.jpg',
    content: `Chiều ngày 12/6, giao thông tại các tuyến phố chính Hà Nội đang ùn tắc kéo dài do lượng phương tiện tăng cao vào giờ cao điểm. Các lực lượng chức năng đã có mặt điều tiết giao thông.`,
    likes: 5,
    comments: 1,
    shares: '3',
  },
  {
    id: 2,
    avatar: '/assets/images/avatar-placeholder.png',
    title: 'Bãi xe 24 Bạch Mai dừng hoạt động từ 4/5/2026',
    date: '3 days ago',
    image: '/assets/images/news_2.jpg',
    content: `Theo thông báo mới nhất, bãi giữ xe tại 24 Bạch Mai sẽ chính thức ngừng hoạt động từ ngày 4/5/2026 để phục vụ dự án cải tạo đô thị. Người dân cần tìm địa điểm gửi xe thay thế.`,
    likes: 10,
    comments: 6,
    shares: '2',
  },
  {
    id: 3,
    avatar: '/assets/images/avatar-placeholder.png',
    title: 'Hà Nội chuẩn bị đón đợt nắng nóng gay gắt',
    date: '1 day ago',
    image: '/assets/images/news_3.jpg',
    content: `Theo Trung tâm Dự báo KTTV, Hà Nội và khu vực miền Bắc sẽ đón đợt nắng nóng với nhiệt độ lên tới 40 độ C, kéo dài trong nhiều ngày. Người dân cần hạn chế ra đường vào buổi trưa.`,
    likes: 15,
    comments: 20,
    shares: '9',
  },
  {
    id: 4,
    avatar: '/assets/images/avatar-placeholder.png',
    title: 'Sở GTVT Hà Nội đề xuất mở rộng tuyến buýt nhanh BRT',
    date: '5 hours ago',
    image: '/assets/images/news_4.jpg',
    content: `Sở GTVT Hà Nội vừa đề xuất mở rộng tuyến buýt nhanh BRT nhằm giảm tải giao thông, tăng khả năng kết nối các khu đô thị mới với trung tâm thành phố.`,
    likes: 21,
    comments: 7,
    shares: '4',
  },
];
