export const NEWS_LIST = [
  {
    id: 1,
    avatar: '/assets/images/avatar-placeholder.png',
    title: 'Update tình trạng giao thông Hà Nội ngày 12 tháng 6',
    date: '12/6/2025',
    image: '/assets/images/news_1.jpg',
    content: `Chiều ngày 12/6, giao thông tại các tuyến phố chính Hà Nội đang ùn tắc kéo dài do lượng phương tiện tăng cao vào giờ cao điểm. Các lực lượng chức năng đã có mặt điều tiết giao thông.`,
    likes: 5,
    comments: 1,
    shares: '3',
  },
  {
    id: 2,
    avatar: '/assets/images/avatar-placeholder.png',
    title: 'Bãi xe 24 Bạch Mai dừng hoạt động từ 4/5/2026',
    date: '23/4/2026',
    image: '/assets/images/news_2.jpg',
    content: `Theo thông báo mới nhất, bãi giữ xe tại 24 Bạch Mai sẽ chính thức ngừng hoạt động từ ngày 4/5/2026 để phục vụ dự án cải tạo đô thị. Người dân cần tìm địa điểm gửi xe thay thế.`,
    likes: 10,
    comments: 6,
    shares: '2',
  },
  {
    id: 3,
    avatar: '/assets/images/avatar-placeholder.png',
    title: 'Hà Nội chuẩn bị đón đợt nắng nóng gay gắt',
    date: '1 day ago',
    image: '/assets/images/news_3.jpg',
    content: `Theo Trung tâm Dự báo KTTV, Hà Nội và khu vực miền Bắc sẽ đón đợt nắng nóng với nhiệt độ lên tới 40 độ C, kéo dài trong nhiều ngày. Người dân cần hạn chế ra đường vào buổi trưa.`,
    likes: 15,
    comments: 20,
    shares: '9',
  },
  {
    id: 4,
    avatar: '/assets/images/avatar-placeholder.png',
    title: 'Sở GTVT Hà Nội đề xuất mở rộng tuyến buýt nhanh BRT',
    date: '2 weeks ago',
    image: '/assets/images/news_4.jpg',
    content: `Sở GTVT Hà Nội vừa đề xuất mở rộng tuyến buýt nhanh BRT nhằm giảm tải giao thông, tăng khả năng kết nối các khu đô thị mới với trung tâm thành phố.`,
    likes: 21,
    comments: 7,
    shares: '4',
  },
  {
    id: 5,
    avatar: '/assets/images/avatar-placeholder.png',
    title: 'Hà Nội tổ chức sát hạch cấp lại GPLX quá hạn',
    date: '7 days ago',
    image: '/assets/images/news_5.jpg',
    content: `Công an Hà Nội đã tổ chức sát hạch GPLX cho người quá hạn hoặc bị trừ hết điểm. Hơn 700 hồ sơ cấp, đổi bằng được tiếp nhận, 61,9% thí sinh đạt yêu cầu.`,
    likes: 12,
    comments: 3,
    shares: '2',
  },
  {
    id: 6,
    avatar: '/assets/images/avatar-placeholder.png',
    title: 'Ô tô gây tai nạn liên hoàn tại Trần Đại Nghĩa - Đại La',
    date: '6 days ago',
    image: '/assets/images/news_6.jpg',
    content: `Một ô tô con tông liên hoàn vào nhiều xe máy tại khu vực Trần Đại Nghĩa - Đại La khiến 6 người bị thương, cây phượng bị đổ và nhiều phương tiện hư hỏng nặng.`,
    likes: 18,
    comments: 12,
    shares: '6',
  },
  {
    id: 7,
    avatar: '/assets/images/avatar-placeholder.png',
    title: 'Tập huấn đăng ký xe cho công an cấp xã tại Hà Nội',
    date: '6 days ago',
    image: '/assets/images/news_7.jpg',
    content: `Hà Nội tổ chức tập huấn nghiệp vụ đăng ký xe cho công an xã. Học viên được hướng dẫn thực hành hệ thống đăng ký xe và kiểm tra cuối khóa để cấp chứng nhận.`,
    likes: 9,
    comments: 1,
    shares: '1',
  },
  {
    id: 8,
    avatar: '/assets/images/avatar-placeholder.png',
    title: 'Hà Nội thí điểm phân làn bằng dải phân cách cứng',
    date: '3 weeks ago',
    image: '/assets/images/news_8.jpg',
    content: `Hà Nội triển khai thí điểm phân làn ô tô, xe máy bằng dải phân cách cứng tại hai tuyến Võ Chí Công và Phạm Văn Đồng nhằm giảm ùn tắc và tai nạn giao thông.`,
    likes: 22,
    comments: 4,
    shares: '3',
  },
  {
    id: 9,
    avatar: '/assets/images/avatar-placeholder.png',
    title: 'Hà Nội cấm xe máy xăng từ tháng 7/2026',
    date: '1 day ago',
    image: '/assets/images/news_9.jpg',
    content: `Từ tháng 7/2026, Hà Nội sẽ cấm xe máy xăng trong Vành đai 1. Thành phố đang giải bài toán hạ tầng sạc điện, hỗ trợ người dân chuyển đổi phương tiện sang xe điện.`,
    likes: 30,
    comments: 15,
    shares: '10',
  },
];
